// <auto-generated />
using System;
using LibraryNET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryNET.Migrations.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LibraryNET.Data.Entities.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BookDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CommissionedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("DecommissionReason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DecommissionedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookDetailsId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.BookAuthor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BookAuthors");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.BookBorrowing", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemindedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId", "UserId");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("BookBorrowings");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.BookBorrowingHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookBorrowingsHistory");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.BookDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookDetails");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnregisteredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.UserDetails", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(55)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.Book", b =>
                {
                    b.HasOne("LibraryNET.Data.Entities.BookDetails", "BookDetails")
                        .WithMany("Books")
                        .HasForeignKey("BookDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookDetails");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.BookBorrowing", b =>
                {
                    b.HasOne("LibraryNET.Data.Entities.Book", "Book")
                        .WithOne("BookBorrowing")
                        .HasForeignKey("LibraryNET.Data.Entities.BookBorrowing", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryNET.Data.Entities.User", "User")
                        .WithMany("BookBorrowings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.BookBorrowingHistory", b =>
                {
                    b.HasOne("LibraryNET.Data.Entities.Book", "Book")
                        .WithMany("BookBorrowingHistory")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryNET.Data.Entities.User", "User")
                        .WithMany("BookBorrowingHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.BookDetails", b =>
                {
                    b.HasOne("LibraryNET.Data.Entities.BookAuthor", "Author")
                        .WithMany("BookDetails")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.UserDetails", b =>
                {
                    b.HasOne("LibraryNET.Data.Entities.User", "User")
                        .WithOne("UserDetails")
                        .HasForeignKey("LibraryNET.Data.Entities.UserDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.Book", b =>
                {
                    b.Navigation("BookBorrowing");

                    b.Navigation("BookBorrowingHistory");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.BookAuthor", b =>
                {
                    b.Navigation("BookDetails");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.BookDetails", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryNET.Data.Entities.User", b =>
                {
                    b.Navigation("BookBorrowingHistory");

                    b.Navigation("BookBorrowings");

                    b.Navigation("UserDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
